### ISSUE TITLE
Add isConnected as delegate method

### ISSUE THREAD

**Issue by Jasperav** [rabbitmq/rabbitmq-objc-client#143] opened 2018-10-27 13:38 UTC
When a user is connected through recovery, I am notified by the following delegate method:

`public func recoveredConnection(_ connection: RMQConnection!) { ... }`

However, there is some time between starting a connection and receiving a callback if the connection is successful or not. I only get notified by a delegate method if a connection has failed. How am I supposed to know if a connection is still being made, or is successful? If an extra method isConnected could be added as delegate method, I can determine the current state of the connection:

- (Re-)Connecting (this state isn't possible without the new delegate method)
- Connected (this state isn't possible without the new delegate method)
- Failed

The delegate method can be added here (I think):

`RMQConnection.m, line 301`

Is it possible to make an else statement and call the new delegate method isConnected? I am having trouble getting the project compiling because I am missing files (local problems).

Edit: there is a completion handler available when starting the connection, but it gets called even before the handshake. A state property that indicates the state of the connection would be useful.

**Comment by michaelklishin** [comment] 2018-10-27 17:18
This is a duplicate of #133. Bunny, the client this one is modelled after, has `Bunny::Session#open?` and `Bunny::Session#connecting?`, and their implementation is [more or less straightforward](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/session.rb#L405).

A PR that adds those methods (with tests please) would be welcome. A specific idea can be discussed in #133 before we move on to writing any code.

**Closed by michaelklishin** 2018-10-27 17:18 UTC
