### ISSUE TITLE
[RMQQueuingConnectionDelegateProxy retain cycle

### ISSUE THREAD

**Issue by 541278903** [rabbitmq/rabbitmq-objc-client#207] opened 2022-08-11 08:59 UTC
in file "RMQQueuingConnectionDelegateProxy.h"

property   id<RMQConnectionDelegate> delegate  need to use  weak

use weak to fix retain cycle

**Comment by michaelklishin** [comment] 2022-08-11 11:07
Duplicate of #206. You again provided no evidence, filing duplicate issues will get you banned from this org.

**Closed by michaelklishin** 2022-08-11 11:07 UTC

**Comment by michaelklishin** [comment] 2022-08-11 11:19
@541278903 if you understand what the problem is, please submit a PR. This is open source software. I'd be happy to run all test suites for you.

Claims that "X has to do Y" leave maintainers guessing, and we do not guess on this team.

**Comment by 541278903** [comment] 2022-08-18 09:54
OK，i will do better next
