### ISSUE TITLE
RMQQueuingConnectionDelegateProxy  retain cycle

### ISSUE THREAD

**Issue by 541278903** [rabbitmq/rabbitmq-objc-client#206] opened 2022-08-11 03:56 UTC
"RMQQueuingConnectionDelegateProxy.h"

@property (nonatomic, readwrite) id<RMQConnectionDelegate> delegate;❌

@property (nonatomic, readwrite, weak) id<RMQConnectionDelegate> delegate; ✅

**Comment by michaelklishin** [comment] 2022-08-11 04:33
@541278903 submitting an issue to the wrong repo without any details, data or evidence ❌
Submitting to a [pull request](https://github.com/rabbitmq/rabbitmq-objc-client/discussions/194) to the right repo with [evidence from diagnostics tools](https://github.com/rabbitmq/rabbitmq-objc-client/discussions/194) ✅

**Comment by michaelklishin** [comment] 2022-08-11 04:36
Without further evidence I'd assume that this is a duplicate of #197.

**Closed by michaelklishin** 2022-08-11 04:36 UTC
