### ISSUE TITLE
GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" 

### ISSUE THREAD

**Issue by oxshabi** [rabbitmq/rabbitmq-objc-client#117] opened 2017-03-31 02:25 UTC
<RMQConnection: 0x1742e9400> disconnectedWithError: Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}

What is the problem？

**Comment by michaelklishin** [comment] 2017-03-31 09:49
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment] 2017-03-31 09:49
I believe "Socket closed by remote peer" is fairly self-descriptive.

**Closed by michaelklishin** 2017-03-31 09:49 UTC

**Comment by iRiziya** [comment] 2021-07-21 13:16
I faced the same issue while integrating using Swift. 

[This is how I resolved it](https://stackoverflow.com/questions/68434935/unable-to-connect-to-remote-rabbitmq-server-using-swift/68466810#68466810)

If that helps someone.
